/**
 * Permission codes the UI checks. The backend seeds the full catalog
 * (`GET /iam/permissions`, doc §5); this file lists only the codes a screen
 * branches on, so a typo is a compile error instead of a silently hidden button.
 *
 * Format: `MODULE.RESOURCE.ACTION`.
 */
export const PERMISSIONS = {
  IAM_USER_READ: 'IAM.USER.READ',
  IAM_USER_CREATE: 'IAM.USER.CREATE',
  IAM_USER_UPDATE: 'IAM.USER.UPDATE',
  IAM_USER_CHANGE_STATUS: 'IAM.USER.CHANGE_STATUS',
  IAM_USER_RESET_CREDENTIALS: 'IAM.USER.RESET_CREDENTIALS',
  IAM_USER_MANAGE_ACCESS: 'IAM.USER.MANAGE_ACCESS',
  IAM_USER_MANAGE_SESSIONS: 'IAM.USER.MANAGE_SESSIONS',
  IAM_USER_EXPORT: 'IAM.USER.EXPORT',

  IAM_ROLE_READ: 'IAM.ROLE.READ',
  IAM_ROLE_CREATE: 'IAM.ROLE.CREATE',
  IAM_ROLE_UPDATE: 'IAM.ROLE.UPDATE',
  IAM_ROLE_DELETE: 'IAM.ROLE.DELETE',
  IAM_ROLE_MANAGE_MEMBERS: 'IAM.ROLE.MANAGE_MEMBERS',

  IAM_GROUP_READ: 'IAM.PERMISSION_GROUP.READ',
  IAM_GROUP_CREATE: 'IAM.PERMISSION_GROUP.CREATE',
  IAM_GROUP_UPDATE: 'IAM.PERMISSION_GROUP.UPDATE',
  IAM_GROUP_DELETE: 'IAM.PERMISSION_GROUP.DELETE',

  IAM_AUDIT_READ: 'IAM.AUDIT.READ',
  IAM_AUDIT_EXPORT: 'IAM.AUDIT.EXPORT',

  IAM_POLICY_READ: 'IAM.SECURITY_POLICY.READ',
  IAM_POLICY_UPDATE: 'IAM.SECURITY_POLICY.UPDATE',

  CATALOG_ALLERGEN_MANAGE: 'CATALOG.ALLERGEN.MANAGE',
  /** Platform-wide (SYSTEM) ingredient catalog — names, allergens, reference prices. */
  CATALOG_INGREDIENT_MANAGE: 'CATALOG.INGREDIENT.MANAGE',
  INGREDIENT_CREATE: 'INGREDIENT.INGREDIENT.CREATE',
  INGREDIENT_UPDATE: 'INGREDIENT.INGREDIENT.UPDATE',
  INGREDIENT_DELETE: 'INGREDIENT.INGREDIENT.DELETE',
  RECIPE_CREATE: 'RECIPE.RECIPE.CREATE',
  RECIPE_UPDATE: 'RECIPE.RECIPE.UPDATE',
  RECIPE_DELETE: 'RECIPE.RECIPE.DELETE',

  FINANCE_CURRENCY_READ: 'FINANCE.CURRENCY.READ',
  FINANCE_CURRENCY_MANAGE: 'FINANCE.CURRENCY.MANAGE',
  FINANCE_TAX_READ: 'FINANCE.TAX_RATE.READ',
  FINANCE_TAX_MANAGE: 'FINANCE.TAX_RATE.MANAGE',
  FINANCE_SETTINGS_UPDATE: 'FINANCE.SETTINGS.UPDATE',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * Transitional mapping used only while access tokens minted before the
 * `permissions` claim are still in circulation (doc §1.4). Once every token
 * carries the claim this table is dead and can be deleted.
 *
 * SUPER_ADMIN is not listed: it is always granted everything.
 */
export const LEGACY_ROLE_PERMISSIONS: Readonly<Record<string, readonly string[]>> = {
  ADMIN: [
    PERMISSIONS.IAM_USER_READ,
    PERMISSIONS.IAM_USER_CREATE,
    PERMISSIONS.IAM_USER_UPDATE,
    PERMISSIONS.IAM_USER_CHANGE_STATUS,
    PERMISSIONS.IAM_USER_RESET_CREDENTIALS,
    PERMISSIONS.IAM_USER_MANAGE_ACCESS,
    PERMISSIONS.IAM_USER_MANAGE_SESSIONS,
    PERMISSIONS.IAM_USER_EXPORT,
    PERMISSIONS.IAM_ROLE_READ,
    PERMISSIONS.IAM_GROUP_READ,
    PERMISSIONS.IAM_AUDIT_READ,
    PERMISSIONS.FINANCE_CURRENCY_READ,
    PERMISSIONS.FINANCE_TAX_READ,
    PERMISSIONS.CATALOG_ALLERGEN_MANAGE,
    PERMISSIONS.CATALOG_INGREDIENT_MANAGE,
    PERMISSIONS.INGREDIENT_CREATE,
    PERMISSIONS.INGREDIENT_UPDATE,
    PERMISSIONS.INGREDIENT_DELETE,
    PERMISSIONS.RECIPE_CREATE,
    PERMISSIONS.RECIPE_UPDATE,
    PERMISSIONS.RECIPE_DELETE,
  ],
  MANAGER: [
    PERMISSIONS.FINANCE_CURRENCY_READ,
    PERMISSIONS.FINANCE_TAX_READ,
    PERMISSIONS.INGREDIENT_CREATE,
    PERMISSIONS.INGREDIENT_UPDATE,
    PERMISSIONS.INGREDIENT_DELETE,
    PERMISSIONS.RECIPE_CREATE,
    PERMISSIONS.RECIPE_UPDATE,
    PERMISSIONS.RECIPE_DELETE,
  ],
  USER: [
    PERMISSIONS.INGREDIENT_CREATE,
    PERMISSIONS.INGREDIENT_UPDATE,
    PERMISSIONS.INGREDIENT_DELETE,
    PERMISSIONS.RECIPE_CREATE,
    PERMISSIONS.RECIPE_UPDATE,
    PERMISSIONS.RECIPE_DELETE,
  ],
};
